export const importantSchoolDates = [
  {
    id: 1,
    from: "01.10.2025",
    to: "03.10.2025",
    days: "",
    justification: "Projekttage Bad Goisern",
  },
  {
    id: 2,
    from: "",
    to: "14.10.2025",
    days: "",
    justification: "Fotografin",
  },
  {
    id: 3,
    from: "",
    to: "15.10.2025",
    days: "",
    justification: "Schulforum (für Elternvertretung)",
  },
  {
    id: 4,
    from: "",
    to: "17.11.2025",
    days: "",
    justification: "Schwimmtraining Biesenfeldbad",
  },
  {
    id: 5,
    from: "",
    to: "24.11.2025",
    days: "",
    justification: "Schwimmtraining Biesenfeldbad",
  },
  {
    id: 6,
    from: "",
    to: "01.12.2025",
    days: "",
    justification: "Schwimmtraining Biesenfeldbad",
  },
  {
    id: 7,
    from: "02.12.2025",
    to: "03.12.2025",
    days: "",
    justification: "Elternsprechtage",
  },
  {
    id: 8,
    from: "",
    to: "15.12.2025",
    days: "",
    justification: "Schwimmtraining Biesenfeldbad",
  },
  {
    id: 9,
    from: "17.12.2025",
    to: "19.12.2025",
    days: "",
    justification: "Skikurs",
  },
  {
    id: 10,
    from: "",
    to: "10.03.2026",
    days: "",
    justification: "Die Reise zum Mittelpunkt des Waldes - Landestheater",
  },
  {
    id: 11,
    from: "12.05.2026",
    to: "13.05.2026",
    days: "",
    justification: "Elternsprechtage",
  }
]
